version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=password
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data: